### ISSUE TITLE
xubuntu 16.04

### ISSUE THREAD

**Issue by coolemza** [scarygliders/X11RDP-o-Matic#59]
everything ok except it cant build deb files
```
Traceback (most recent call last):
  File "/usr/bin/dh_make", line 851, in <module>
    main()
  File "/usr/bin/dh_make", line 845, in main
    if confirm_fields(args, subs):
  File "/usr/bin/dh_make", line 544, in confirm_fields
    choice = getch()
  File "/usr/bin/dh_make", line 350, in getch
    oldterm = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')
./X11rdp-o-matic.sh: line 471: cd: debian: No such file or directory
rm: cannot remove '*.ex': No such file or directory
rm: cannot remove '*.EX': No such file or directory
rm: cannot remove 'README.Debian': No such file or directory
rm: cannot remove 'README.source': No such file or directory
cp: cannot stat '../COPYING': No such file or directory
cp: cannot stat '../readme.txt': No such file or directory
----------------------------------------------------------------------
Preparation complete. Building and packaging xrdp...
----------------------------------------------------------------------
dpkg-buildpackage: warning: using a gain-root-command while being root
tail: cannot open 'debian/changelog' for reading: No such file or directory
dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1
mv: cannot stat 'xrdp*.deb': No such file or directory
./X11rdp-o-matic.sh: line 993: /etc/init.d/xrdp: No such file or directory
dpkg: error processing archive /home/lc/Projects/X11RDP-o-Matic/packages/Xorg/*.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 /home/lc/Projects/X11RDP-o-Matic/packages/Xorg/*.deb
dpkg: error processing archive /home/lc/Projects/X11RDP-o-Matic/packages/xrdp/xrdp*.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 /home/lc/Projects/X11RDP-o-Matic/packages/xrdp/xrdp*.deb
----------------------------------------------------------------------
X11rdp and xrdp should now be fully installed, configured, and running on this system.
One last thing to do now is to configure which desktop will be presented to the user after they log in via RDP.
You may not have to do this - test by logging into xrdp now.
Or use the RDPsesconfig.sh utility to configure a session's desktop.
----------------------------------------------------------------------
```

**Comment by coolemza** [comment]
it the same bug as #60
